//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;

namespace Ulangan.walahi
{
    public interface IForm1
    {
        static abstract CultureInfo Culture { get; set; }
        static abstract ResourceManager ResourceManager { get; }
    }
}